// Lokale SQLite-Migrationen (idempotent). Jede Migration hat eine Version;
// angewandte Versionen stehen in local_schema_migrations.
export interface LocalMigration { version: number; name: string; sql: string }

export const MIGRATIONS: LocalMigration[] = [
  {
    version: 1,
    name: 'create_local_training_sessions',
    sql: `create table if not exists local_training_sessions (
      local_id text primary key,
      remote_id text,
      user_id text,
      dog_id text,
      category text,
      type text,
      status text,
      title text,
      notes text,
      score real,
      visibility text,
      started_at text,
      ended_at text,
      duration_seconds integer,
      location_name text,
      latitude real,
      longitude real,
      temperature real,
      weather_condition text,
      wind_speed real,
      humidity real,
      surface_types text,
      terrain_conditions text,
      created_at text,
      updated_at text,
      deleted_at text,
      sync_status text,
      sync_attempts integer default 0,
      last_sync_error text,
      last_synced_at text,
      dirty_fields text,
      payload_json text
    );`,
  },
  {
    version: 2,
    name: 'create_local_track_points',
    sql: `create table if not exists local_track_points (
      local_id text primary key,
      remote_id text,
      session_local_id text not null,
      session_remote_id text,
      latitude real,
      longitude real,
      accuracy real,
      altitude real,
      speed real,
      heading real,
      timestamp text,
      point_type text,
      created_at text,
      sync_status text,
      payload_json text
    );
    create index if not exists idx_ltp_session on local_track_points (session_local_id);`,
  },
  {
    version: 3,
    name: 'create_local_track_markers',
    sql: `create table if not exists local_track_markers (
      local_id text primary key,
      remote_id text,
      session_local_id text not null,
      session_remote_id text,
      marker_type text,
      material text,
      latitude real,
      longitude real,
      accuracy real,
      distance_from_start real,
      note text,
      audio_local_uri text,
      audio_remote_url text,
      created_at text,
      sync_status text,
      payload_json text
    );
    create index if not exists idx_ltm_session on local_track_markers (session_local_id);`,
  },
  {
    version: 4,
    name: 'create_local_media_files',
    sql: `create table if not exists local_media_files (
      local_id text primary key,
      remote_id text,
      session_local_id text,
      session_remote_id text,
      file_type text,
      local_uri text,
      remote_url text,
      mime_type text,
      file_size integer,
      duration_seconds integer,
      width integer,
      height integer,
      created_at text,
      sync_status text,
      upload_attempts integer default 0,
      last_upload_error text,
      metadata_json text
    );`,
  },
  {
    version: 5,
    name: 'create_sync_queue',
    sql: `create table if not exists sync_queue (
      id text primary key,
      entity_type text not null,
      entity_local_id text not null,
      operation text not null,
      priority integer default 5,
      payload_json text,
      created_at text,
      updated_at text,
      attempts integer default 0,
      last_error text,
      status text default 'pending'
    );
    create index if not exists idx_sq_status on sync_queue (status, priority);`,
  },
];
